In [80]:
# import pandas as pd
# import numpy as np 
# data = 'Student Habits vs Academic Performance Study (ការសិក្សាអំពីទម្លាប់របស់និស្សិត និងលទ្ធផលសិក្សា) (Responses) - Form responses (2) - Student Habits vs Academic Performance Study (ការសិក្សាអំពីទម្លាប់របស់និស្សិត និងលទ្ធផ.csv'
# df = pd.read_csv(data)

In [81]:

# import re

# def extract_midpoint(value):
#     if pd.isna(value):
#         return None
    
#     value = str(value).strip().lower()

   
#     single = re.match(r'^(\d+(?:\.\d+)?)\s*(hours?|days?|%)?$', value)
#     if single:
#         return float(single.group(1))

    
#     if "less than 1" in value:
#         return 0.5

  
#     less = re.match(r'less than (\d+)', value)
#     if less:
#         return float(less.group(1)) - 1

#     plus = re.match(r'(\d+)\+', value)
#     if plus:
#         return float(plus.group(1))

#     range_match = re.search(r'(\d+(?:\.\d+)?)\s*[–\-]\s*(\d+(?:\.\d+)?)', value)
#     if range_match:
#         lo = float(range_match.group(1))
#         hi = float(range_match.group(2))
#         return (lo + hi) / 2

#     return None  
# range_cols = [
#     "Self_Study_Hrs",
#     "Tutoring_Hrs_Wk",
#     "Social_Media_Hrs",
#     "Gaming_Hrs",
#     "Exercise_Days_Wk",
#     "Sleep_Hrs",
# ]

# for col in range_cols:
#     df[col] = df[col].apply(extract_midpoint)

# def parse_attendance(value):
#     if pd.isna(value):
#         return None
#     value = str(value).strip().lower().replace('%', '')
#     if "below 60" in value:
#         return 55.0
#     range_match = re.search(r'(\d+)\s*[–\-]\s*(\d+)', value)
#     if range_match:
#         return (float(range_match.group(1)) + float(range_match.group(2))) / 2
#     return None

# df["Attendance_Rate"] = df["Attendance_Rate"].apply(parse_attendance)
# def parse_stress(value):
#     if pd.isna(value):
#         return None
#     range_match = re.search(r'(\d+)\s*[–\-]\s*(\d+)', str(value))
#     if range_match:
#         return (float(range_match.group(1)) + float(range_match.group(2))) / 2
#     return None

# df["Stress_Level"] = df["Stress_Level"].apply(parse_stress)


# numeric_cols = ["Stress_Level", "Self_Study_Hrs", "Tutoring_Hrs_Wk",
#                 "Social_Media_Hrs", "Gaming_Hrs", "Exercise_Days_Wk",
#                 "Sleep_Hrs", "Attendance_Rate"]

# print(df[numeric_cols].dtypes)
# print("\nSample output:")
# print(df[numeric_cols].head(10).to_string())
# print("\nMissing values:")
# print(df[numeric_cols].isnull().sum())

In [82]:
# df.to_csv("Predicting Academic Achievement in Cambodian Higher Education.csv", index=False)

In [83]:
import pandas as pd
data = 'Predicting Academic Achievement in Cambodian Higher Education.csv'
df = pd.read_csv(data)

In [84]:
df.head()

,Gender,Age,Hometown,University,Year,STEM_Major,Diet_Quality,Internet_Quality,Employment,Study_Habit,...,Social_Media_Hrs,Gaming_Hrs,Exercise_Days_Wk,Sleep_Hrs,Attendance_Rate,Commute_Time,Study_Group_Freq,Extracurricular,GPA,Performance_Tier
0,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,good,good,Unemployed / Full-time student,Cramming,...,1.5,0.5,3.5,7.0,95.0,15–30 minutes,Rarely (Before exams only),Yes,3.39,Very Good / Good
1,Female,22,Province (Rural / Semi-Urban),American University Of Phnom Penh(AUPP),Year 1,Yes,excellent,good,Unemployed / Full-time student,Regular study,...,1.5,0.0,3.5,8.0,95.0,15–30 minutes,Rarely (Before exams only),No,3.69,Very Good / Good
2,Male,18,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 1,Yes,Average,good,Unemployed / Full-time student,Irregular study,...,3.5,1.5,1.5,7.0,95.0,Under 15 minutes,Sometimes (Weekly),Yes,3.48,Very Good / Good
3,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,good,good,Unemployed / Full-time student,Regular study,...,3.5,0.5,0.0,5.0,82.0,15–30 minutes,Sometimes (Weekly),Yes,3.50,Very Good / Good
4,Male,20,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,Average,Fair,Unemployed / Full-time student,Regular study,...,3.5,1.5,1.5,6.0,82.0,More than 1 hour,Sometimes (Weekly),Yes,3.70,Very Good / Good

In [85]:
df.describe()

,Age,Stress_Level,Self_Study_Hrs,Tutoring_Hrs_Wk,Social_Media_Hrs,Gaming_Hrs,Exercise_Days_Wk,Sleep_Hrs,Attendance_Rate,GPA
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,495.000000
mean,20.754000,6.332000,2.460000,1.790000,3.038000,1.479000,2.343000,6.166000,81.436000,2.850586
std,2.596723,2.036682,1.354648,2.173557,1.522232,1.448881,1.740376,1.307618,13.801844,0.664395
min,17.000000,1.500000,0.000000,0.000000,0.500000,0.000000,0.000000,4.000000,55.000000,2.000000
25%,19.000000,5.500000,1.000000,0.000000,1.500000,0.500000,1.500000,5.000000,67.000000,2.270000
50%,20.000000,5.500000,2.000000,1.500000,3.500000,1.500000,1.500000,6.000000,82.000000,2.480000
75%,23.000000,7.500000,3.000000,2.000000,5.000000,1.500000,3.500000,7.000000,95.000000,3.500000
max,39.000000,9.500000,6.000000,10.000000,5.000000,5.000000,5.000000,9.000000,95.000000,4.000000

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gender            500 non-null    str
 1   Age               500 non-null    int64
 2   Hometown          500 non-null    str
 3   University        500 non-null    str
 4   Year              500 non-null    str
 5   STEM_Major        500 non-null    str
 6   Diet_Quality      500 non-null    str
 7   Internet_Quality  500 non-null    str
 8   Employment        500 non-null    str
 9   Study_Habit       500 non-null    str
 10  Stress_Level      500 non-null    float64
 11  Self_Study_Hrs    500 non-null    float64
 12  Tutoring_Hrs_Wk   500 non-null    float64
 13  AI_Tool_Usage     500 non-null    str
 14  Social_Media_Hrs  500 non-null    float64
 15  Gaming_Hrs        500 non-null    float64
 16  Exercise_Days_Wk  500 non-null    float64
 17  Sleep_Hrs         500 non-null    float64
 18  Attendance_Rate   500 non-null    float64
 19  Commute_Time      500 non-null    str
 20  Study_Group_Freq  500 non-null    str
 21  Extracurricular   500 non-null    str
 22  GPA               495 non-null    float64
 23  Performance_Tier  500 non-null    str
dtypes: float64(9), int64(1), str(14)
memory usage: 93.9 KB

In [87]:
df.isna().sum()

Gender              0
Age                 0
Hometown            0
University          0
Year                0
STEM_Major          0
Diet_Quality        0
Internet_Quality    0
Employment          0
Study_Habit         0
Stress_Level        0
Self_Study_Hrs      0
Tutoring_Hrs_Wk     0
AI_Tool_Usage       0
Social_Media_Hrs    0
Gaming_Hrs          0
Exercise_Days_Wk    0
Sleep_Hrs           0
Attendance_Rate     0
Commute_Time        0
Study_Group_Freq    0
Extracurricular     0
GPA                 5
Performance_Tier    0
dtype: int64

In [88]:
df["GPA"].fillna(df["GPA"].median(), inplace=True)
df

C:\Users\MSI\AppData\Local\Temp\ipykernel_10232\1356799445.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["GPA"].fillna(df["GPA"].median(), inplace=True)

,Gender,Age,Hometown,University,Year,STEM_Major,Diet_Quality,Internet_Quality,Employment,Study_Habit,...,Social_Media_Hrs,Gaming_Hrs,Exercise_Days_Wk,Sleep_Hrs,Attendance_Rate,Commute_Time,Study_Group_Freq,Extracurricular,GPA,Performance_Tier
0,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,good,good,Unemployed / Full-time student,Cramming,...,1.5,0.5,3.5,7.0,95.0,15–30 minutes,Rarely (Before exams only),Yes,3.39,Very Good / Good
1,Female,22,Province (Rural / Semi-Urban),American University Of Phnom Penh(AUPP),Year 1,Yes,excellent,good,Unemployed / Full-time student,Regular study,...,1.5,0.0,3.5,8.0,95.0,15–30 minutes,Rarely (Before exams only),No,3.69,Very Good / Good
2,Male,18,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 1,Yes,Average,good,Unemployed / Full-time student,Irregular study,...,3.5,1.5,1.5,7.0,95.0,Under 15 minutes,Sometimes (Weekly),Yes,3.48,Very Good / Good
3,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,good,good,Unemployed / Full-time student,Regular study,...,3.5,0.5,0.0,5.0,82.0,15–30 minutes,Sometimes (Weekly),Yes,3.50,Very Good / Good
4,Male,20,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,Average,Fair,Unemployed / Full-time student,Regular study,...,3.5,1.5,1.5,6.0,82.0,More than 1 hour,Sometimes (Weekly),Yes,3.70,Very Good / Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Male,23,Phnom Penh (Urban),Build Bright University(BBU),Year 2,Yes,Good,Good,Working part-time,Irregular study,...,5.0,0.5,1.5,4.0,82.0,Over 1 hour,Rarely (Before exams only),No,2.35,At Risk
496,Male,18,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 3,Yes,Good,Average,Working part-time,Irregular study,...,1.5,0.0,3.5,7.0,95.0,31–60 minutes,Rarely (Before exams only),Yes,3.63,Very Good / Good
497,Female,24,Phnom Penh (Urban),Royal University of Phnom Penh(RUPP),Year 2,No,Good,Poor,Unemployed / Full-time student,Irregular study,...,3.5,1.5,3.5,6.0,95.0,Under 15 minutes,Rarely (Before exams only),Yes,3.39,Fair / Average
498,Male,21,Province (Rural / Semi-Urban),American University Of Phnom Penh(AUPP),Year 2,No,Average,Excellent,Unemployed / Full-time student,Regular study,...,5.0,0.0,1.5,7.0,95.0,15–30 minutes,Rarely (Before exams only),No,3.36,Fair / Average
499,Female,20,Province (Rural / Semi-Urban),American University Of Phnom Penh(AUPP),Year 3,No,Average,Poor,Working part-time,No fixed habit,...,5.0,3.5,1.5,6.0,82.0,Over 1 hour,Rarely (Before exams only),No,2.16,At Risk

In [89]:
df.isnull().sum()

Gender              0
Age                 0
Hometown            0
University          0
Year                0
STEM_Major          0
Diet_Quality        0
Internet_Quality    0
Employment          0
Study_Habit         0
Stress_Level        0
Self_Study_Hrs      0
Tutoring_Hrs_Wk     0
AI_Tool_Usage       0
Social_Media_Hrs    0
Gaming_Hrs          0
Exercise_Days_Wk    0
Sleep_Hrs           0
Attendance_Rate     0
Commute_Time        0
Study_Group_Freq    0
Extracurricular     0
GPA                 5
Performance_Tier    0
dtype: int64

In [90]:
df.duplicated().any()
df.drop_duplicates(keep='first', inplace=True)
df.shape

(498, 24)

In [91]:
df['GPA']=df['GPA'].fillna(df['GPA'].median(), inplace=True)
df.isnull().sum()

C:\Users\MSI\AppData\Local\Temp\ipykernel_10232\1698864038.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['GPA']=df['GPA'].fillna(df['GPA'].median(), inplace=True)

Gender              0
Age                 0
Hometown            0
University          0
Year                0
STEM_Major          0
Diet_Quality        0
Internet_Quality    0
Employment          0
Study_Habit         0
Stress_Level        0
Self_Study_Hrs      0
Tutoring_Hrs_Wk     0
AI_Tool_Usage       0
Social_Media_Hrs    0
Gaming_Hrs          0
Exercise_Days_Wk    0
Sleep_Hrs           0
Attendance_Rate     0
Commute_Time        0
Study_Group_Freq    0
Extracurricular     0
GPA                 0
Performance_Tier    0
dtype: int64

In [92]:
def gpa_to_tier(gpa):
    if pd.isna(gpa):
        return None
    elif gpa < 2.5:
        return "At-Risk"
    elif gpa < 3.0:
        return "Fair / Average"
    elif gpa < 3.5:
        return "Very Good / Good"
    else:
        return "Outstanding / Excellent"

df["Performance_Tier"] = df["GPA"].apply(gpa_to_tier)  # ✅ this is all you need

print("Tier distribution:")
print(df["Performance_Tier"].value_counts())

print("\nSample check:")
print(df[["GPA", "Performance_Tier"]].sort_values("GPA").head(100).to_string())

Tier distribution:
Performance_Tier
At-Risk                    255
Outstanding / Excellent    128
Very Good / Good            84
Fair / Average              31
Name: count, dtype: int64

Sample check:
      GPA Performance_Tier
44   2.00          At-Risk
47   2.00          At-Risk
277  2.00          At-Risk
131  2.00          At-Risk
233  2.01          At-Risk
448  2.01          At-Risk
270  2.01          At-Risk
298  2.01          At-Risk
257  2.01          At-Risk
322  2.02          At-Risk
323  2.02          At-Risk
331  2.02          At-Risk
110  2.02          At-Risk
402  2.02          At-Risk
194  2.02          At-Risk
222  2.02          At-Risk
290  2.04          At-Risk
139  2.04          At-Risk
164  2.05          At-Risk
170  2.05          At-Risk
304  2.05          At-Risk
100  2.06          At-Risk
287  2.06          At-Risk
346  2.06          At-Risk
228  2.07          At-Risk
320  2.07          At-Risk
446  2.07          At-Risk
224  2.07          At-Risk
466  2.08          At-Risk
369  2.08          At-Risk
264  2.08          At-Risk
451  2.09          At-Risk
117  2.09          At-Risk
175  2.09          At-Risk
340  2.09          At-Risk
293  2.09          At-Risk
316  2.10          At-Risk
286  2.10          At-Risk
247  2.11          At-Risk
311  2.11          At-Risk
186  2.11          At-Risk
182  2.11          At-Risk
488  2.12          At-Risk
329  2.12          At-Risk
107  2.12          At-Risk
259  2.12          At-Risk
192  2.12          At-Risk
152  2.12          At-Risk
291  2.13          At-Risk
305  2.13          At-Risk
279  2.13          At-Risk
163  2.13          At-Risk
123  2.14          At-Risk
269  2.14          At-Risk
158  2.14          At-Risk
253  2.14          At-Risk
399  2.14          At-Risk
485  2.14          At-Risk
374  2.15          At-Risk
386  2.15          At-Risk
149  2.15          At-Risk
405  2.15          At-Risk
292  2.15          At-Risk
98   2.15          At-Risk
189  2.15          At-Risk
428  2.15          At-Risk
409  2.15          At-Risk
167  2.16          At-Risk
137  2.16          At-Risk
499  2.16          At-Risk
385  2.17          At-Risk
260  2.17          At-Risk
388  2.17          At-Risk
343  2.17          At-Risk
455  2.17          At-Risk
353  2.18          At-Risk
475  2.18          At-Risk
413  2.18          At-Risk
274  2.18          At-Risk
122  2.18          At-Risk
120  2.18          At-Risk
172  2.18          At-Risk
103  2.18          At-Risk
99   2.18          At-Risk
145  2.19          At-Risk
159  2.19          At-Risk
352  2.19          At-Risk
479  2.19          At-Risk
199  2.19          At-Risk
101  2.19          At-Risk
317  2.19          At-Risk
441  2.20          At-Risk
237  2.20          At-Risk
173  2.20          At-Risk
456  2.20          At-Risk
434  2.21          At-Risk
334  2.21          At-Risk
181  2.21          At-Risk
109  2.22          At-Risk
218  2.22          At-Risk

In [93]:
df

,Gender,Age,Hometown,University,Year,STEM_Major,Diet_Quality,Internet_Quality,Employment,Study_Habit,...,Social_Media_Hrs,Gaming_Hrs,Exercise_Days_Wk,Sleep_Hrs,Attendance_Rate,Commute_Time,Study_Group_Freq,Extracurricular,GPA,Performance_Tier
0,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,good,good,Unemployed / Full-time student,Cramming,...,1.5,0.5,3.5,7.0,95.0,15–30 minutes,Rarely (Before exams only),Yes,3.39,Very Good / Good
1,Female,22,Province (Rural / Semi-Urban),American University Of Phnom Penh(AUPP),Year 1,Yes,excellent,good,Unemployed / Full-time student,Regular study,...,1.5,0.0,3.5,8.0,95.0,15–30 minutes,Rarely (Before exams only),No,3.69,Outstanding / Excellent
2,Male,18,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 1,Yes,Average,good,Unemployed / Full-time student,Irregular study,...,3.5,1.5,1.5,7.0,95.0,Under 15 minutes,Sometimes (Weekly),Yes,3.48,Very Good / Good
3,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,good,good,Unemployed / Full-time student,Regular study,...,3.5,0.5,0.0,5.0,82.0,15–30 minutes,Sometimes (Weekly),Yes,3.50,Outstanding / Excellent
4,Male,20,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,Average,Fair,Unemployed / Full-time student,Regular study,...,3.5,1.5,1.5,6.0,82.0,More than 1 hour,Sometimes (Weekly),Yes,3.70,Outstanding / Excellent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Male,23,Phnom Penh (Urban),Build Bright University(BBU),Year 2,Yes,Good,Good,Working part-time,Irregular study,...,5.0,0.5,1.5,4.0,82.0,Over 1 hour,Rarely (Before exams only),No,2.35,At-Risk
496,Male,18,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 3,Yes,Good,Average,Working part-time,Irregular study,...,1.5,0.0,3.5,7.0,95.0,31–60 minutes,Rarely (Before exams only),Yes,3.63,Outstanding / Excellent
497,Female,24,Phnom Penh (Urban),Royal University of Phnom Penh(RUPP),Year 2,No,Good,Poor,Unemployed / Full-time student,Irregular study,...,3.5,1.5,3.5,6.0,95.0,Under 15 minutes,Rarely (Before exams only),Yes,3.39,Very Good / Good
498,Male,21,Province (Rural / Semi-Urban),American University Of Phnom Penh(AUPP),Year 2,No,Average,Excellent,Unemployed / Full-time student,Regular study,...,5.0,0.0,1.5,7.0,95.0,15–30 minutes,Rarely (Before exams only),No,3.36,Very Good / Good
499,Female,20,Province (Rural / Semi-Urban),American University Of Phnom Penh(AUPP),Year 3,No,Average,Poor,Working part-time,No fixed habit,...,5.0,3.5,1.5,6.0,82.0,Over 1 hour,Rarely (Before exams only),No,2.16,At-Risk

In [94]:
df['Study_Habit'].replace('No fixed habit','Irregular study', inplace=True)

C:\Users\MSI\AppData\Local\Temp\ipykernel_10232\2609740271.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Study_Habit'].replace('No fixed habit','Irregular study', inplace=True)

0             Cramming
1        Regular study
2      Irregular study
3        Regular study
4        Regular study
            ...
495    Irregular study
496    Irregular study
497    Irregular study
498      Regular study
499    Irregular study
Name: Study_Habit, Length: 498, dtype: str

In [95]:
df['Study_Habit'].unique()

<StringArray>
['Cramming', 'Regular study', 'Irregular study', 'No fixed habit']
Length: 4, dtype: str

In [96]:
df['University'].unique()

<StringArray>
[     'American University Of Phnom Penh(AUPP)',
     'Institute of Technology of Cambodia(ITC)',
              'De Montfort University Cambodia',
        'Royal University Of Law and Economics',
 'Cambodia Academy Of Digital Technology(CADT)',
         'Royal University Of Phnom Penh(RUPP)',
                                          'UTE',
                           'Paragon University',
                    'University of Puthisastra',
                        'CamEd Business School',
 'Royal University Of Law and Economics (RULE)',
           'University Of Health Science (UHS)',
    'University of Economics and Finance (UEF)',
              'Royal University Of Agriculture',
                    'University of puthisastra',
         'Royal University of Phnom Penh(RUPP)',
                 'Build Bright University(BBU)',
                        'Norton University(NU)',
      'Pannasastra University of Cambodia(PUC)']
Length: 19, dtype: str

In [97]:
df['University'].replace('University of puthisastra', 'University of Puthisastra', inplace=True)

C:\Users\MSI\AppData\Local\Temp\ipykernel_10232\2350490707.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['University'].replace('University of puthisastra', 'University of Puthisastra', inplace=True)

0      American University Of Phnom Penh(AUPP)
1      American University Of Phnom Penh(AUPP)
2      American University Of Phnom Penh(AUPP)
3      American University Of Phnom Penh(AUPP)
4      American University Of Phnom Penh(AUPP)
                        ...
495               Build Bright University(BBU)
496    American University Of Phnom Penh(AUPP)
497       Royal University of Phnom Penh(RUPP)
498    American University Of Phnom Penh(AUPP)
499    American University Of Phnom Penh(AUPP)
Name: University, Length: 498, dtype: str

In [98]:
df['University'].unique()

<StringArray>
[     'American University Of Phnom Penh(AUPP)',
     'Institute of Technology of Cambodia(ITC)',
              'De Montfort University Cambodia',
        'Royal University Of Law and Economics',
 'Cambodia Academy Of Digital Technology(CADT)',
         'Royal University Of Phnom Penh(RUPP)',
                                          'UTE',
                           'Paragon University',
                    'University of Puthisastra',
                        'CamEd Business School',
 'Royal University Of Law and Economics (RULE)',
           'University Of Health Science (UHS)',
    'University of Economics and Finance (UEF)',
              'Royal University Of Agriculture',
                    'University of puthisastra',
         'Royal University of Phnom Penh(RUPP)',
                 'Build Bright University(BBU)',
                        'Norton University(NU)',
      'Pannasastra University of Cambodia(PUC)']
Length: 19, dtype: str

In [99]:
df['Year'].unique()

<StringArray>
['Year 2', 'Year 1', 'Year 3', 'postgraduate education', 'Year 4']
Length: 5, dtype: str

In [100]:
df['Year'] = df['Year'].replace('postgraduate education', 'Year 4',inplace=True)
df['Year'].unique()

C:\Users\MSI\AppData\Local\Temp\ipykernel_10232\77813390.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Year'] = df['Year'].replace('postgraduate education', 'Year 4',inplace=True)

<StringArray>
['Year 2', 'Year 1', 'Year 3', 'Year 4']
Length: 4, dtype: str

In [101]:
# ── 1. Diet_Quality — normalise casing ───────────────────────────────────────
df["Diet_Quality"] = df["Diet_Quality"].str.strip().str.title()
# "good" → "Good", "excellent" → "Excellent", etc.
 
# ── 2. Internet_Quality — normalise casing ───────────────────────────────────
df["Internet_Quality"] = df["Internet_Quality"].str.strip().str.title()
 
# ── 3. University — strip + title to merge the two RUPP spellings ────────────
df["University"] = df["University"].str.strip().str.title()
 
# ── 4. Commute_Time — unify the two ">1 hour" labels ────────────────────────
df["Commute_Time"] = df["Commute_Time"].replace(
    {"More than 1 hour": "Over 1 hour"}
)

In [102]:

print("Diet_Quality:     ", sorted(df["Diet_Quality"].unique()))
print(len(df["Diet_Quality"].unique()))
print("Internet_Quality: ", sorted(df["Internet_Quality"].unique()))
print(len(df["Internet_Quality"].unique()))
print("University:       ", sorted(df["University"].unique()))
print(len(df["University"].unique()))
print("Commute_Time:     ", sorted(df["Commute_Time"].unique()))
print(len(df["Commute_Time"].unique()))
print("Study_Group_Freq: ", sorted(df["Study_Group_Freq"].unique()))
print(len(df["Study_Group_Freq"].unique()))

Diet_Quality:      ['Average', 'Excellent', 'Fair', 'Good', 'Poor']
5
Internet_Quality:  ['Average', 'Excellent', 'Fair', 'Good', 'Poor']
5
University:        ['American University Of Phnom Penh(Aupp)', 'Build Bright University(Bbu)', 'Cambodia Academy Of Digital Technology(Cadt)', 'Camed Business School', 'De Montfort University Cambodia', 'Institute Of Technology Of Cambodia(Itc)', 'Norton University(Nu)', 'Pannasastra University Of Cambodia(Puc)', 'Paragon University', 'Royal University Of Agriculture', 'Royal University Of Law And Economics', 'Royal University Of Law And Economics (Rule)', 'Royal University Of Phnom Penh(Rupp)', 'University Of Economics And Finance (Uef)', 'University Of Health Science (Uhs)', 'University Of Puthisastra', 'Ute']
17
Commute_Time:      ['15–30 minutes', '31–60 minutes', 'Over 1 hour', 'Under 15 minutes']
4
Study_Group_Freq:  ['Frequently (Multiple times a week)', 'Never', 'Often (Daily or near-daily)', 'Rarely (Before exams only)', 'Sometimes (Weekly)']
5

In [103]:
df.to_csv("Academic_Predictor.csv", index=False)