In [1]:
import pandas as pd 
data = 'CambodianStudyHabitandPerformanceCleaned(1).csv'
df = pd.read_csv(data)
df.head(20)

,Gender,Age,Hometown,University,Year,STEM_Major,Diet_Quality,Internet_Quality,Employment,Study_Habit,...,Social_Media_Hrs,Gaming_Hrs,Exercise_Days_Wk,Sleep_Hrs,Attendance_Rate,Commute_Time,Study_Group_Freq,Extracurricular,GPA,Performance_Tier
0,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(Aupp),Year 2,Yes,Good,Good,Unemployed / Full-time student,Cramming,...,1.5,0.5,3.5,7.0,95.0,15–30 minutes,Rarely (Before exams only),Yes,3.39,Very Good / Good
1,Female,22,Province (Rural / Semi-Urban),American University Of Phnom Penh(Aupp),Year 1,Yes,Excellent,Good,Unemployed / Full-time student,Regular study,...,1.5,0.0,3.5,8.0,95.0,15–30 minutes,Rarely (Before exams only),No,3.69,Very Good / Good
2,Male,18,Phnom Penh (Urban),American University Of Phnom Penh(Aupp),Year 1,Yes,Average,Good,Unemployed / Full-time student,Irregular study,...,3.5,1.5,1.5,7.0,95.0,Under 15 minutes,Sometimes (Weekly),Yes,3.48,Very Good / Good
3,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(Aupp),Year 2,Yes,Good,Good,Unemployed / Full-time student,Regular study,...,3.5,0.5,0.0,5.0,82.0,15–30 minutes,Sometimes (Weekly),Yes,3.50,Very Good / Good
4,Male,20,Phnom Penh (Urban),American University Of Phnom Penh(Aupp),Year 2,Yes,Average,Fair,Unemployed / Full-time student,Regular study,...,3.5,1.5,1.5,6.0,82.0,Over 1 hour,Sometimes (Weekly),Yes,3.70,Very Good / Good
5,Male,20,Province (Rural / Semi-Urban),Institute Of Technology Of Cambodia(Itc),Year 3,Yes,Average,Excellent,Unemployed / Full-time student,Regular study,...,5.0,3.5,5.0,5.0,67.0,Under 15 minutes,Sometimes (Weekly),Yes,2.90,Fair / Average
6,Female,19,Province (Rural / Semi-Urban),De Montfort University Cambodia,Year 2,No,Average,Good,Unemployed / Full-time student,Regular study,...,5.0,0.0,0.0,6.0,82.0,Over 1 hour,Frequently (Multiple times a week),No,3.05,Very Good / Good
7,Male,18,Phnom Penh (Urban),Institute Of Technology Of Cambodia(Itc),Year 1,Yes,Good,Poor,Unemployed / Full-time student,Cramming,...,3.5,0.5,5.0,6.0,95.0,Under 15 minutes,Frequently (Multiple times a week),Yes,3.00,Very Good / Good
8,Male,19,Province (Rural / Semi-Urban),Royal University Of Law And Economics,Year 3,No,Average,Fair,Working full-time,Regular study,...,1.5,0.5,1.5,8.0,82.0,15–30 minutes,Sometimes (Weekly),Yes,3.50,Very Good / Good
9,Male,17,Phnom Penh (Urban),American University Of Phnom Penh(Aupp),Year 3,Yes,Good,Poor,Working part-time,Irregular study,...,0.5,3.5,0.0,4.0,95.0,Under 15 minutes,Rarely (Before exams only),No,3.89,Outstanding / Excellent
10,Male,18,Phnom Penh (Urban),Cambodia Academy Of Digital Technology(Cadt),Year 1,Yes,Average,Fair,Working part-time,Regular study,...,5.0,1.5,5.0,5.0,95.0,31–60 minutes,Sometimes (Weekly),Yes,3.05,Very Good / Good
11,Male,20,Phnom Penh (Urban),American University Of Phnom Penh(Aupp),Year 2,Yes,Excellent,Fair,Working full-time,Regular study,...,3.5,0.0,3.5,7.0,95.0,31–60 minutes,Sometimes (Weekly),Yes,3.91,Outstanding / Excellent
12,Female,18,Phnom Penh (Urban),Royal University Of Phnom Penh(Rupp),Year 1,No,Average,Fair,Unemployed / Full-time student,Cramming,...,5.0,0.5,0.0,4.0,95.0,Under 15 minutes,Rarely (Before exams only),Yes,3.05,Very Good / Good
13,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(Aupp),Year 1,No,Average,Fair,Unemployed / Full-time student,Regular study,...,3.5,0.5,3.5,7.0,95.0,31–60 minutes,Frequently (Multiple times a week),Yes,3.44,Very Good / Good
14,Male,19,Phnom Penh (Urban),Ute,Year 1,Yes,Good,Good,Unemployed / Full-time student,Irregular study,...,5.0,1.5,5.0,5.0,95.0,15–30 minutes,Sometimes (Weekly),Yes,3.15,Very Good / Good
15,Male,19,Province (Rural / Semi-Urban),American University Of Phnom Penh(Aupp),Year 2,Yes,Good,Good,Working part-time,Regular study,...,3.5,0.5,3.5,7.0,82.0,15–30 minutes,Rarely (Before exams only),Yes,3.63,Very Good / Good
16,Male,20,Phnom Penh (Urban),American University Of Phnom Penh(Aupp),Year 2,Yes,Good,Good,Working full-time,Irregular study,...,1.5,0.0,5.0,7.0,82.0,Under 15 minutes,Sometimes (Weekly),Yes,3.43,Fair / Average
17,Male,22,Phnom Penh (Urban),Paragon University,Year 3,No,Average,Good,Unemployed / Full-time student,Regular study,...,5.0,1.5,5.0,8.0,95.0,15–30 minutes,Rarely (Before exams only),No,3.20,Fair / Average
18,Female,18,Phnom Penh (Urban),University Of Puthisastra,Year 1,No,Average,Excellent,Unemployed / Full-time student,Irregular study,...,1.5,1.5,1.5,4.0,67.0,Under 15 minutes,Rarely (Before exams only),Yes,4.00,Outstanding / Excellent
19,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(Aupp),Year 2,Yes,Good,Good,Unemployed / Full-time student,Regular study,...,1.5,1.5,1.5,8.0,95.0,31–60 minutes,Sometimes (Weekly),Yes,3.67,Very Good / Good

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 596 entries, 0 to 595
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gender            596 non-null    str
 1   Age               596 non-null    int64
 2   Hometown          596 non-null    str
 3   University        596 non-null    str
 4   Year              596 non-null    str
 5   STEM_Major        596 non-null    str
 6   Diet_Quality      596 non-null    str
 7   Internet_Quality  596 non-null    str
 8   Employment        596 non-null    str
 9   Study_Habit       596 non-null    str
 10  Stress_Level      596 non-null    float64
 11  Self_Study_Hrs    596 non-null    float64
 12  Tutoring_Hrs_Wk   596 non-null    float64
 13  AI_Tool_Usage     596 non-null    str
 14  Social_Media_Hrs  596 non-null    float64
 15  Gaming_Hrs        596 non-null    float64
 16  Exercise_Days_Wk  596 non-null    float64
 17  Sleep_Hrs         596 non-null    float64
 18  Attendance_Rate   596 non-null    float64
 19  Commute_Time      596 non-null    str
 20  Study_Group_Freq  596 non-null    str
 21  Extracurricular   596 non-null    str
 22  GPA               596 non-null    float64
 23  Performance_Tier  596 non-null    str
dtypes: float64(9), int64(1), str(14)
memory usage: 111.9 KB

In [3]:
df.describe()

,Age,Stress_Level,Self_Study_Hrs,Tutoring_Hrs_Wk,Social_Media_Hrs,Gaming_Hrs,Exercise_Days_Wk,Sleep_Hrs,Attendance_Rate,GPA
count,596.000000,596.000000,596.000000,596.000000,596.000000,596.000000,596.000000,596.000000,596.000000,596.000000
mean,20.093960,6.057047,2.605705,1.625839,2.979866,1.221477,2.122483,6.201342,86.775168,2.973674
std,1.647375,1.904908,1.505363,2.623604,1.502803,1.387680,1.715015,1.240655,12.192288,0.731863
min,17.000000,1.500000,0.000000,0.000000,0.500000,0.000000,0.000000,4.000000,55.000000,1.200000
25%,19.000000,5.500000,1.000000,0.000000,1.500000,0.000000,1.500000,5.000000,82.000000,2.560000
50%,20.000000,5.500000,3.000000,0.000000,3.500000,0.500000,1.500000,6.000000,95.000000,3.050000
75%,21.000000,7.500000,4.000000,2.000000,3.500000,1.500000,3.500000,7.000000,95.000000,3.580000
max,39.000000,9.500000,6.000000,10.000000,5.000000,5.000000,5.000000,9.000000,95.000000,4.000000

In [4]:
categorical_columns = df.select_dtypes(include=['object']).columns
categorical_columns

C:\Users\MSI\AppData\Local\Temp\ipykernel_18032\2864691023.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object']).columns

Index(['Gender', 'Hometown', 'University', 'Year', 'STEM_Major',
       'Diet_Quality', 'Internet_Quality', 'Employment', 'Study_Habit',
       'AI_Tool_Usage', 'Commute_Time', 'Study_Group_Freq', 'Extracurricular',
       'Performance_Tier'],
      dtype='str')

In [5]:
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns
numerical_columns

Index(['Age', 'Stress_Level', 'Self_Study_Hrs', 'Tutoring_Hrs_Wk',
       'Social_Media_Hrs', 'Gaming_Hrs', 'Exercise_Days_Wk', 'Sleep_Hrs',
       'Attendance_Rate', 'GPA'],
      dtype='str')

Feature engineer

In [6]:
commute_map = {
    'Under 15 minutes': 0.125,  # midpoint of 0–15 min
    '15–30 minutes':    0.375,  # midpoint of 15–30 min
    '31–60 minutes':    0.75,   # midpoint of 31–60 min
    'Over 1 hour':      1.25    # reasonable estimate for 60–90 min
}
study_group_map = {
    'Never':                              0,
    'Rarely (Before exams only)':         1,
    'Sometimes (Weekly)':                 2,
    'Frequently (Multiple times a week)': 3
}
study_habit_map = {
    'Cramming':        1,
    'Irregular study': 2,
    'Regular study':   3
}

commute_hrs = df['Commute_Time'].map(commute_map)
study_group_num = df['Study_Group_Freq'].map(study_group_map)
study_habit_num = df['Study_Habit'].map(study_habit_map)
extracurricular_num = df['Extracurricular'].map({'Yes': 1, 'No': 0})

# --- Feature 1: Total Productive Hours ---
df['Total_Productive_Hrs'] = df['Self_Study_Hrs'] + df['Tutoring_Hrs_Wk']

# --- Feature 2: Distraction Hours ---
df['Distraction_Hrs'] = df['Social_Media_Hrs'] + df['Gaming_Hrs']

# --- Feature 3: Study-to-Distraction Ratio ---
df['Study_Distraction_Ratio'] = df['Self_Study_Hrs'] / (df['Distraction_Hrs'] + 0.1)  # +0.1 avoid div by zero

# --- Feature 4: Wellbeing Score ---
df['Wellbeing_Score'] = df['Sleep_Hrs'] + df['Exercise_Days_Wk'] - df['Stress_Level']

# --- Feature 5: Available Study Time ---
df['Available_Study_Time'] = 24 - df['Sleep_Hrs'] - df['Social_Media_Hrs'] - df['Gaming_Hrs'] - commute_hrs

# --- Feature 6: Active Engagement Score ---
df['Active_Engagement_Score'] = df['Attendance_Rate'] / 10 + study_group_num + extracurricular_num

# --- Feature 7: Study Quality Flag ---
df['Study_Quality'] = study_habit_num * df['Self_Study_Hrs']

print(df[['Total_Productive_Hrs', 'Distraction_Hrs', 'Study_Distraction_Ratio',
          'Wellbeing_Score', 'Available_Study_Time', 'Active_Engagement_Score',
          'Study_Quality']].head())

   Total_Productive_Hrs  Distraction_Hrs  Study_Distraction_Ratio  \
0                   4.0              2.0                 1.904762
1                   2.0              1.5                 1.250000
2                   5.0              5.0                 0.588235
3                   2.0              4.0                 0.487805
4                   4.0              5.0                 0.784314

   Wellbeing_Score  Available_Study_Time  Active_Engagement_Score  \
0              5.0                14.625                     11.5
1              6.0                14.125                     10.5
2              1.0                11.875                     12.5
3             -0.5                14.625                     11.2
4              0.0                11.750                     11.2

   Study_Quality
0            4.0
1            6.0
2            6.0
3            6.0
4           12.0

In [7]:
df

,Gender,Age,Hometown,University,Year,STEM_Major,Diet_Quality,Internet_Quality,Employment,Study_Habit,...,Extracurricular,GPA,Performance_Tier,Total_Productive_Hrs,Distraction_Hrs,Study_Distraction_Ratio,Wellbeing_Score,Available_Study_Time,Active_Engagement_Score,Study_Quality
0,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(Aupp),Year 2,Yes,Good,Good,Unemployed / Full-time student,Cramming,...,Yes,3.39,Very Good / Good,4.0,2.0,1.904762,5.0,14.625,11.5,4.0
1,Female,22,Province (Rural / Semi-Urban),American University Of Phnom Penh(Aupp),Year 1,Yes,Excellent,Good,Unemployed / Full-time student,Regular study,...,No,3.69,Very Good / Good,2.0,1.5,1.250000,6.0,14.125,10.5,6.0
2,Male,18,Phnom Penh (Urban),American University Of Phnom Penh(Aupp),Year 1,Yes,Average,Good,Unemployed / Full-time student,Irregular study,...,Yes,3.48,Very Good / Good,5.0,5.0,0.588235,1.0,11.875,12.5,6.0
3,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(Aupp),Year 2,Yes,Good,Good,Unemployed / Full-time student,Regular study,...,Yes,3.50,Very Good / Good,2.0,4.0,0.487805,-0.5,14.625,11.2,6.0
4,Male,20,Phnom Penh (Urban),American University Of Phnom Penh(Aupp),Year 2,Yes,Average,Fair,Unemployed / Full-time student,Regular study,...,Yes,3.70,Very Good / Good,4.0,5.0,0.784314,0.0,11.750,11.2,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591,Female,18,Province (Rural / Semi-Urban),American University Of Phnom Penh(Aupp),Year 3,Yes,Average,Fair,Unemployed / Full-time student,Regular study,...,No,3.96,Outstanding / Excellent,9.0,3.5,1.111111,5.0,13.375,9.5,12.0
592,Male,21,Province (Rural / Semi-Urban),American University Of Phnom Penh(Aupp),Year 1,Yes,Good,Fair,Unemployed / Full-time student,Regular study,...,No,3.93,Outstanding / Excellent,3.0,3.5,0.277778,6.0,12.125,10.5,3.0
593,Male,19,Province (Rural / Semi-Urban),American University Of Phnom Penh(Aupp),Year 1,Yes,Good,Good,Unemployed / Full-time student,Regular study,...,No,3.98,Outstanding / Excellent,4.0,6.5,0.606061,4.0,9.375,12.5,12.0
594,Male,20,Phnom Penh (Urban),Paragon University,Year 2,Yes,Good,Good,Working part-time,Regular study,...,No,3.63,Outstanding / Excellent,6.0,5.0,0.784314,5.0,11.625,12.5,12.0
595,Male,20,Province (Rural / Semi-Urban),Institute Of Technology Of Cambodia(Itc),Year 3,Yes,Good,Fair,Unemployed / Full-time student,Regular study,...,Yes,3.50,Outstanding / Excellent,6.0,4.0,0.975610,4.5,12.250,11.5,12.0

In [8]:
# Drop high cardinality & leakage
df.drop(columns=['Age', 'University', 'Hometown'], inplace=True)

# Binary
df['Gender']     = df['Gender'].map({'Male': 1, 'Female': 0})
df['STEM_Major'] = df['STEM_Major'].map({'Yes': 1, 'No': 0})

# Ordinal
df['Employment'] = df['Employment'].map({
    'Unemployed / Full-time student': 0,
    'Working part-time':              1,
    'Working full-time':              2
})
df['Diet_Quality'] = df['Diet_Quality'].map({
    'Poor': 1, 'Average': 2, 'Good': 3, 'Excellent': 4
})
df['Internet_Quality'] = df['Internet_Quality'].map({
    'Poor': 1, 'Fair': 2, 'Good': 3, 'Excellent': 4
})
df['AI_Tool_Usage'] = df['AI_Tool_Usage'].map({
    'Never': 0, 'Rarely': 1, 'Sometimes': 2, 'Often': 3, 'Always': 4
})
df['Year'] = df['Year'].map({
    'Year 1': 1, 'Year 2': 2, 'Year 3': 3, 'Year 4': 4
})
# Save the mapped columns back into df
df['Study_Habit']      = study_habit_num
df['Study_Group_Freq'] = study_group_num
df['Commute_Time']     = commute_hrs
df['Extracurricular']  = extracurricular_num

print(df.dtypes)
print(df.head())

Gender                       int64
Year                         int64
STEM_Major                   int64
Diet_Quality                 int64
Internet_Quality             int64
Employment                   int64
Study_Habit                  int64
Stress_Level               float64
Self_Study_Hrs             float64
Tutoring_Hrs_Wk            float64
AI_Tool_Usage                int64
Social_Media_Hrs           float64
Gaming_Hrs                 float64
Exercise_Days_Wk           float64
Sleep_Hrs                  float64
Attendance_Rate            float64
Commute_Time               float64
Study_Group_Freq             int64
Extracurricular              int64
GPA                        float64
Performance_Tier               str
Total_Productive_Hrs       float64
Distraction_Hrs            float64
Study_Distraction_Ratio    float64
Wellbeing_Score            float64
Available_Study_Time       float64
Active_Engagement_Score    float64
Study_Quality              float64
dtype: object
   Gender  Year  STEM_Major  Diet_Quality  Internet_Quality  Employment  \
0       1     2           1             3                 3           0
1       0     1           1             4                 3           0
2       1     1           1             2                 3           0
3       1     2           1             3                 3           0
4       1     2           1             2                 2           0

   Study_Habit  Stress_Level  Self_Study_Hrs  Tutoring_Hrs_Wk  ...  \
0            1           5.5             4.0              0.0  ...
1            3           5.5             2.0              0.0  ...
2            2           7.5             3.0              2.0  ...
3            3           5.5             2.0              0.0  ...
4            3           7.5             4.0              0.0  ...

   Extracurricular   GPA  Performance_Tier  Total_Productive_Hrs  \
0                1  3.39  Very Good / Good                   4.0
1                0  3.69  Very Good / Good                   2.0
2                1  3.48  Very Good / Good                   5.0
3                1  3.50  Very Good / Good                   2.0
4                1  3.70  Very Good / Good                   4.0

   Distraction_Hrs  Study_Distraction_Ratio  Wellbeing_Score  \
0              2.0                 1.904762              5.0
1              1.5                 1.250000              6.0
2              5.0                 0.588235              1.0
3              4.0                 0.487805             -0.5
4              5.0                 0.784314              0.0

   Available_Study_Time  Active_Engagement_Score  Study_Quality
0                14.625                     11.5            4.0
1                14.125                     10.5            6.0
2                11.875                     12.5            6.0
3                14.625                     11.2            6.0
4                11.750                     11.2           12.0

[5 rows x 28 columns]

In [9]:
df['Performance_Tier'].unique()

<StringArray>
['Very Good / Good', 'Fair / Average', 'Outstanding / Excellent', 'At-Risk']
Length: 4, dtype: str

In [10]:
performance_tier_map = {
    'At-Risk': 0,
    'Fair / Average': 1,
    'Very Good / Good' : 1,
    'Outstanding / Excellent': 2
}
df['Performance_Tier'] = df['Performance_Tier'].map(performance_tier_map)

In [11]:
df

,Gender,Year,STEM_Major,Diet_Quality,Internet_Quality,Employment,Study_Habit,Stress_Level,Self_Study_Hrs,Tutoring_Hrs_Wk,...,Extracurricular,GPA,Performance_Tier,Total_Productive_Hrs,Distraction_Hrs,Study_Distraction_Ratio,Wellbeing_Score,Available_Study_Time,Active_Engagement_Score,Study_Quality
0,1,2,1,3,3,0,1,5.5,4.0,0.0,...,1,3.39,1,4.0,2.0,1.904762,5.0,14.625,11.5,4.0
1,0,1,1,4,3,0,3,5.5,2.0,0.0,...,0,3.69,1,2.0,1.5,1.250000,6.0,14.125,10.5,6.0
2,1,1,1,2,3,0,2,7.5,3.0,2.0,...,1,3.48,1,5.0,5.0,0.588235,1.0,11.875,12.5,6.0
3,1,2,1,3,3,0,3,5.5,2.0,0.0,...,1,3.50,1,2.0,4.0,0.487805,-0.5,14.625,11.2,6.0
4,1,2,1,2,2,0,3,7.5,4.0,0.0,...,1,3.70,1,4.0,5.0,0.784314,0.0,11.750,11.2,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591,0,3,1,2,2,0,3,5.5,4.0,5.0,...,0,3.96,2,9.0,3.5,1.111111,5.0,13.375,9.5,12.0
592,1,1,1,3,2,0,3,5.5,1.0,2.0,...,0,3.93,2,3.0,3.5,0.277778,6.0,12.125,10.5,3.0
593,1,1,1,3,3,0,3,5.5,4.0,0.0,...,0,3.98,2,4.0,6.5,0.606061,4.0,9.375,12.5,12.0
594,1,2,1,3,3,1,3,3.5,4.0,2.0,...,0,3.63,2,6.0,5.0,0.784314,5.0,11.625,12.5,12.0
595,1,3,1,3,2,0,3,7.5,4.0,2.0,...,1,3.50,2,6.0,4.0,0.975610,4.5,12.250,11.5,12.0

In [12]:
df.drop(columns=[
    'Self_Study_Hrs',    # → Total_Productive_Hrs, Study_Quality, Study_Distraction_Ratio
    'Tutoring_Hrs_Wk',  # → Total_Productive_Hrs
    'Social_Media_Hrs', # → Distraction_Hrs, Available_Study_Time
    'Gaming_Hrs',       # → Distraction_Hrs, Available_Study_Time
    'Sleep_Hrs',        # → Wellbeing_Score, Available_Study_Time
    'Exercise_Days_Wk', # → Wellbeing_Score
    'Attendance_Rate',  # → Active_Engagement_Score
    'Study_Habit',      # → Study_Quality
    'Study_Group_Freq', # → Active_Engagement_Score
    'Commute_Time',     # → Available_Study_Time
    'Extracurricular',  # → Active_Engagement_Score
], inplace=True)
df

,Gender,Year,STEM_Major,Diet_Quality,Internet_Quality,Employment,Stress_Level,AI_Tool_Usage,GPA,Performance_Tier,Total_Productive_Hrs,Distraction_Hrs,Study_Distraction_Ratio,Wellbeing_Score,Available_Study_Time,Active_Engagement_Score,Study_Quality
0,1,2,1,3,3,0,5.5,3,3.39,1,4.0,2.0,1.904762,5.0,14.625,11.5,4.0
1,0,1,1,4,3,0,5.5,4,3.69,1,2.0,1.5,1.250000,6.0,14.125,10.5,6.0
2,1,1,1,2,3,0,7.5,3,3.48,1,5.0,5.0,0.588235,1.0,11.875,12.5,6.0
3,1,2,1,3,3,0,5.5,4,3.50,1,2.0,4.0,0.487805,-0.5,14.625,11.2,6.0
4,1,2,1,2,2,0,7.5,4,3.70,1,4.0,5.0,0.784314,0.0,11.750,11.2,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591,0,3,1,2,2,0,5.5,4,3.96,2,9.0,3.5,1.111111,5.0,13.375,9.5,12.0
592,1,1,1,3,2,0,5.5,3,3.93,2,3.0,3.5,0.277778,6.0,12.125,10.5,3.0
593,1,1,1,3,3,0,5.5,4,3.98,2,4.0,6.5,0.606061,4.0,9.375,12.5,12.0
594,1,2,1,3,3,1,3.5,2,3.63,2,6.0,5.0,0.784314,5.0,11.625,12.5,12.0
595,1,3,1,3,2,0,7.5,4,3.50,2,6.0,4.0,0.975610,4.5,12.250,11.5,12.0

In [13]:
from sklearn.feature_selection import SelectKBest, chi2, f_classif 
X = df.drop(['Performance_Tier','GPA'], axis=1)
Y = df['Performance_Tier']
selector = SelectKBest(score_func=f_classif, k=12)
selector.fit(X, Y)
selected_features = selector.get_feature_names_out(input_features=X.columns)
print("Selected Features:", selected_features)

Selected Features: ['Diet_Quality' 'Internet_Quality' 'Employment' 'Stress_Level'
 'AI_Tool_Usage' 'Total_Productive_Hrs' 'Distraction_Hrs'
 'Study_Distraction_Ratio' 'Wellbeing_Score' 'Available_Study_Time'
 'Active_Engagement_Score' 'Study_Quality']

In [14]:
df['Performance_Tier'].unique()

array([1, 2, 0])

In [15]:
df.to_csv('preprocessed_data(1).csv', index=False)