In [37]:
import pandas as pd 
data = r'C:\Users\MSI\ML-final-project\Academic-Predictor-machine-based-on-performance-\data\raw_data\Cambodian_Students_habit_and_performance.csv'
df = pd.read_csv(data)
df.head(20)

,Gender,Age,Hometown,University,Year,STEM_Major,Diet_Quality,Internet_Quality,Employment,Study_Habit,...,Social_Media_Hrs,Gaming_Hrs,Exercise_Days_Wk,Sleep_Hrs,Attendance_Rate,Commute_Time,Study_Group_Freq,Extracurricular,GPA,Performance_Tier
0,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,good,good,Unemployed / Full-time student,Cramming,...,1.5,0.5,3.5,7.0,95.0,15–30 minutes,Rarely (Before exams only),Yes,3.39,Very Good / Good
1,Female,22,Province (Rural / Semi-Urban),American University Of Phnom Penh(AUPP),Year 1,Yes,excellent,good,Unemployed / Full-time student,Regular study,...,1.5,0.0,3.5,8.0,95.0,15–30 minutes,Rarely (Before exams only),No,3.69,Very Good / Good
2,Male,18,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 1,Yes,Average,good,Unemployed / Full-time student,Irregular study,...,3.5,1.5,1.5,7.0,95.0,Under 15 minutes,Sometimes (Weekly),Yes,3.48,Very Good / Good
3,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,good,good,Unemployed / Full-time student,Regular study,...,3.5,0.5,0.0,5.0,82.0,15–30 minutes,Sometimes (Weekly),Yes,3.50,Very Good / Good
4,Male,20,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,Average,Fair,Unemployed / Full-time student,Regular study,...,3.5,1.5,1.5,6.0,82.0,More than 1 hour,Sometimes (Weekly),Yes,3.70,Very Good / Good
5,Male,20,Province (Rural / Semi-Urban),Institute of Technology of Cambodia(ITC),Year 3,Yes,Average,Excellent,Unemployed / Full-time student,Regular study,...,5.0,3.5,5.0,5.0,67.0,Under 15 minutes,Sometimes (Weekly),Yes,2.90,Fair / Average
6,Female,19,Province (Rural / Semi-Urban),De Montfort University Cambodia,Year 2,No,Average,good,Unemployed / Full-time student,Regular study,...,5.0,0.0,0.0,6.0,82.0,More than 1 hour,Frequently (Multiple times a week),No,NaN,Very Good / Good
7,Male,18,Phnom Penh (Urban),Institute of Technology of Cambodia(ITC),Year 1,Yes,good,Poor,Unemployed / Full-time student,Cramming,...,3.5,0.5,5.0,6.0,95.0,Under 15 minutes,Frequently (Multiple times a week),Yes,3.00,Very Good / Good
8,Male,19,Province (Rural / Semi-Urban),Royal University Of Law and Economics,Year 3,No,Average,Fair,Working full-time,Regular study,...,1.5,0.5,1.5,8.0,82.0,15–30 minutes,Sometimes (Weekly),Yes,3.50,Very Good / Good
9,Male,17,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 3,Yes,good,Poor,Working part-time,Irregular study,...,0.5,3.5,0.0,4.0,95.0,Under 15 minutes,Rarely (Before exams only),No,3.89,Outstanding / Excellent
10,Male,18,Phnom Penh (Urban),Cambodia Academy Of Digital Technology(CADT),Year 1,Yes,Average,Fair,Working part-time,Regular study,...,5.0,1.5,5.0,5.0,95.0,31–60 minutes,Sometimes (Weekly),Yes,NaN,Very Good / Good
11,Male,20,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,excellent,Fair,Working full-time,Regular study,...,3.5,0.0,3.5,7.0,95.0,31–60 minutes,Sometimes (Weekly),Yes,3.91,Outstanding / Excellent
12,Female,18,Phnom Penh (Urban),Royal University Of Phnom Penh(RUPP),Year 1,No,Average,Fair,Unemployed / Full-time student,Cramming,...,5.0,0.5,0.0,4.0,95.0,Under 15 minutes,Rarely (Before exams only),Yes,NaN,Very Good / Good
13,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 1,No,Average,Fair,Unemployed / Full-time student,Regular study,...,3.5,0.5,3.5,7.0,95.0,31–60 minutes,Frequently (Multiple times a week),Yes,3.44,Very Good / Good
14,Male,19,Phnom Penh (Urban),UTE,Year 1,Yes,good,good,Unemployed / Full-time student,Irregular study,...,5.0,1.5,5.0,5.0,95.0,15–30 minutes,Sometimes (Weekly),Yes,3.15,Very Good / Good
15,Male,19,Province (Rural / Semi-Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,good,good,Working part-time,Regular study,...,3.5,0.5,3.5,7.0,82.0,15–30 minutes,Rarely (Before exams only),Yes,3.63,Very Good / Good
16,Male,20,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,good,good,Working full-time,Irregular study,...,1.5,0.0,5.0,7.0,82.0,Under 15 minutes,Sometimes (Weekly),Yes,3.43,Fair / Average
17,Male,22,Phnom Penh (Urban),Paragon University,Year 3,No,Average,good,Unemployed / Full-time student,Regular study,...,5.0,1.5,5.0,8.0,95.0,15–30 minutes,Rarely (Before exams only),No,3.20,Fair / Average
18,Female,18,Phnom Penh (Urban),University of Puthisastra,Year 1,No,Average,Excellent,Unemployed / Full-time student,Irregular study,...,1.5,1.5,1.5,4.0,67.0,Under 15 minutes,Rarely (Before exams only),Yes,4.00,Outstanding / Excellent
19,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,good,good,Unemployed / Full-time student,Regular study,...,1.5,1.5,1.5,8.0,95.0,31–60 minutes,Sometimes (Weekly),Yes,3.67,Very Good / Good

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 598 entries, 0 to 597
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gender            598 non-null    object
 1   Age               598 non-null    int64
 2   Hometown          598 non-null    object
 3   University        598 non-null    object
 4   Year              598 non-null    object
 5   STEM_Major        598 non-null    object
 6   Diet_Quality      598 non-null    object
 7   Internet_Quality  598 non-null    object
 8   Employment        598 non-null    object
 9   Study_Habit       598 non-null    object
 10  Stress_Level      598 non-null    float64
 11  Self_Study_Hrs    598 non-null    float64
 12  Tutoring_Hrs_Wk   598 non-null    float64
 13  AI_Tool_Usage     598 non-null    object
 14  Social_Media_Hrs  598 non-null    float64
 15  Gaming_Hrs        598 non-null    float64
 16  Exercise_Days_Wk  598 non-null    float64
 17  Sleep_Hrs         598 non-null    float64
 18  Attendance_Rate   598 non-null    float64
 19  Commute_Time      598 non-null    object
 20  Study_Group_Freq  598 non-null    object
 21  Extracurricular   598 non-null    object
 22  GPA               593 non-null    float64
 23  Performance_Tier  598 non-null    object
dtypes: float64(9), int64(1), object(14)
memory usage: 112.3+ KB

In [39]:
df.isnull().sum()

Gender              0
Age                 0
Hometown            0
University          0
Year                0
STEM_Major          0
Diet_Quality        0
Internet_Quality    0
Employment          0
Study_Habit         0
Stress_Level        0
Self_Study_Hrs      0
Tutoring_Hrs_Wk     0
AI_Tool_Usage       0
Social_Media_Hrs    0
Gaming_Hrs          0
Exercise_Days_Wk    0
Sleep_Hrs           0
Attendance_Rate     0
Commute_Time        0
Study_Group_Freq    0
Extracurricular     0
GPA                 5
Performance_Tier    0
dtype: int64

In [40]:
df.describe()

,Age,Stress_Level,Self_Study_Hrs,Tutoring_Hrs_Wk,Social_Media_Hrs,Gaming_Hrs,Exercise_Days_Wk,Sleep_Hrs,Attendance_Rate,GPA
count,598.000000,598.000000,598.000000,598.000000,598.000000,598.000000,598.000000,598.000000,598.000000,593.000000
mean,20.093645,6.055184,2.603679,1.620401,2.974916,1.217391,2.127090,6.204013,86.802676,2.973120
std,1.644623,1.901986,1.503247,2.620890,1.502719,1.387150,1.713989,1.239435,12.181123,0.733683
min,17.000000,1.500000,0.000000,0.000000,0.500000,0.000000,0.000000,4.000000,55.000000,1.200000
25%,19.000000,5.500000,1.000000,0.000000,1.500000,0.000000,1.500000,5.000000,82.000000,2.560000
50%,20.000000,5.500000,3.000000,0.000000,3.500000,0.500000,1.500000,6.000000,95.000000,3.050000
75%,21.000000,7.500000,4.000000,2.000000,3.500000,1.500000,3.500000,7.000000,95.000000,3.580000
max,39.000000,9.500000,6.000000,10.000000,5.000000,5.000000,5.000000,9.000000,95.000000,4.000000

In [41]:
categorical_columns = df.select_dtypes(include=['object']).columns
categorical_columns

Index(['Gender', 'Hometown', 'University', 'Year', 'STEM_Major',
       'Diet_Quality', 'Internet_Quality', 'Employment', 'Study_Habit',
       'AI_Tool_Usage', 'Commute_Time', 'Study_Group_Freq', 'Extracurricular',
       'Performance_Tier'],
      dtype='object')

In [42]:
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns
numerical_columns

Index(['Age', 'Stress_Level', 'Self_Study_Hrs', 'Tutoring_Hrs_Wk',
       'Social_Media_Hrs', 'Gaming_Hrs', 'Exercise_Days_Wk', 'Sleep_Hrs',
       'Attendance_Rate', 'GPA'],
      dtype='object')

Feature engineer

In [43]:
commute_map = {
    'Under 15 minutes':  0.125,
    '15–30 minutes':     0.375,
    '31–60 minutes':     0.75,
    'More than 1 hour':  1.25   # ← was 'Over 1 hour' before
}
study_group_map = {
    'Never':                               0,
    'Rarely (Before exams only)':          1,
    'Sometimes (Weekly)':                  2,
    'Frequently (Multiple times a week)': 3
}
study_habit_map = {
    'Cramming':        1,
    'Irregular study': 2,
    'Regular study':   3
}
ai_usage_map = { 
    'Never': 0,
    'Rarely': 1,
    'Sometimes': 2,
    'Often': 3,
    'Always': 4
}

# 2. Map directly back into the DataFrame (or keep as standalone Series)
commute_hrs = df['Commute_Time'].map(commute_map)
study_group_num = df['Study_Group_Freq'].map(study_group_map)
study_habit_num = df['Study_Habit'].map(study_habit_map)
extracurricular_num = df['Extracurricular'].map({'Yes': 1, 'No': 0})
ai_tool_usage_num = df['AI_Tool_Usage'].map(ai_usage_map)

# --- Feature 1: Total Productive Hours ---
df['Total_Productive_Hrs'] = df['Self_Study_Hrs'] + df['Tutoring_Hrs_Wk']

# --- Feature 2: Distraction Hours ---
df['Distraction_Hrs'] = df['Social_Media_Hrs'] + df['Gaming_Hrs']

# --- Feature 3: Study-to-Distraction Ratio ---
df['Study_Distraction_Ratio'] = df['Self_Study_Hrs'] / (df['Distraction_Hrs'] + 0.1)

# --- Feature 4: Wellbeing Score ---
df['Wellbeing_Score'] = df['Sleep_Hrs'] + df['Exercise_Days_Wk'] - df['Stress_Level']

# --- Feature 5: Available Study Time ---
df['Available_Study_Time'] = 24 - df['Sleep_Hrs'] - df['Social_Media_Hrs'] - df['Gaming_Hrs'] - commute_hrs

# --- Feature 6: Active Engagement Score ---
df['Active_Engagement_Score'] = df['Attendance_Rate'] / 10 + study_group_num + extracurricular_num

# --- Feature 7: Study Quality Flag ---
df['Study_Quality'] = study_habit_num * df['Self_Study_Hrs']

# --- FIXED Feature 8: AI Enhanced Study ---
# Use the mapped numeric Series (ai_tool_usage_num) instead of the raw text column
df['AI_Enhanced_Study'] = df['Self_Study_Hrs'] * ai_tool_usage_num

# Print results
print(df[['Total_Productive_Hrs', 'Distraction_Hrs', 'Study_Distraction_Ratio',
          'Wellbeing_Score', 'Available_Study_Time', 'Active_Engagement_Score',
          'Study_Quality', 'AI_Enhanced_Study']].head())

   Total_Productive_Hrs  Distraction_Hrs  Study_Distraction_Ratio  \
0                   4.0              2.0                 1.904762
1                   2.0              1.5                 1.250000
2                   5.0              5.0                 0.588235
3                   2.0              4.0                 0.487805
4                   4.0              5.0                 0.784314

   Wellbeing_Score  Available_Study_Time  Active_Engagement_Score  \
0              5.0                14.625                     11.5
1              6.0                14.125                     10.5
2              1.0                11.875                     12.5
3             -0.5                14.625                     11.2
4              0.0                11.750                     11.2

   Study_Quality  AI_Enhanced_Study
0            4.0               12.0
1            6.0                8.0
2            6.0                9.0
3            6.0                8.0
4           12.0               16.0

In [44]:
df

,Gender,Age,Hometown,University,Year,STEM_Major,Diet_Quality,Internet_Quality,Employment,Study_Habit,...,GPA,Performance_Tier,Total_Productive_Hrs,Distraction_Hrs,Study_Distraction_Ratio,Wellbeing_Score,Available_Study_Time,Active_Engagement_Score,Study_Quality,AI_Enhanced_Study
0,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,good,good,Unemployed / Full-time student,Cramming,...,3.39,Very Good / Good,4.0,2.0,1.904762,5.0,14.625,11.5,4.0,12.0
1,Female,22,Province (Rural / Semi-Urban),American University Of Phnom Penh(AUPP),Year 1,Yes,excellent,good,Unemployed / Full-time student,Regular study,...,3.69,Very Good / Good,2.0,1.5,1.250000,6.0,14.125,10.5,6.0,8.0
2,Male,18,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 1,Yes,Average,good,Unemployed / Full-time student,Irregular study,...,3.48,Very Good / Good,5.0,5.0,0.588235,1.0,11.875,12.5,6.0,9.0
3,Male,19,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,good,good,Unemployed / Full-time student,Regular study,...,3.50,Very Good / Good,2.0,4.0,0.487805,-0.5,14.625,11.2,6.0,8.0
4,Male,20,Phnom Penh (Urban),American University Of Phnom Penh(AUPP),Year 2,Yes,Average,Fair,Unemployed / Full-time student,Regular study,...,3.70,Very Good / Good,4.0,5.0,0.784314,0.0,11.750,11.2,12.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,Female,18,Province (Rural / Semi-Urban),American University Of Phnom Penh(AUPP),Year 3,Yes,Average,Fair,Unemployed / Full-time student,Regular study,...,3.96,Outstanding / Excellent,9.0,3.5,1.111111,5.0,13.375,9.5,12.0,16.0
594,Male,21,Province (Rural / Semi-Urban),American University Of Phnom Penh(AUPP),Year 1,Yes,good,Fair,Unemployed / Full-time student,Regular study,...,3.93,Outstanding / Excellent,3.0,3.5,0.277778,6.0,12.125,10.5,3.0,3.0
595,Male,19,Province (Rural / Semi-Urban),American University Of Phnom Penh(AUPP),Year 1,Yes,good,good,Unemployed / Full-time student,Regular study,...,3.98,Outstanding / Excellent,4.0,6.5,0.606061,4.0,9.375,12.5,12.0,16.0
596,Male,20,Phnom Penh (Urban),Paragon University,Year 2,Yes,good,good,Working part-time,Regular study,...,3.63,Outstanding / Excellent,6.0,5.0,0.784314,5.0,11.625,12.5,12.0,8.0
597,Male,20,Province (Rural / Semi-Urban),Institute of Technology of Cambodia(ITC),Year 3,Yes,good,Fair,Unemployed / Full-time student,Regular study,...,3.50,Outstanding / Excellent,6.0,4.0,0.975610,4.5,12.250,11.5,12.0,16.0

In [45]:
# Drop high cardinality & leakage
df.drop(columns=['Age', 'University', 'Hometown'], inplace=True)

# Binary
df['Gender']     = df['Gender'].map({'Male': 1, 'Female': 0})
df['STEM_Major'] = df['STEM_Major'].map({'Yes': 1, 'No': 0})

# Ordinal
df['Employment'] = df['Employment'].map({
    'Unemployed / Full-time student': 0,
    'Working part-time':              1,
    'Working full-time':              2
})
df['Diet_Quality'] = df['Diet_Quality'].str.strip().str.lower().map({
    'poor': 1, 'average': 2, 'good': 3, 'excellent': 4
})

df['Internet_Quality'] = df['Internet_Quality'].str.strip().str.lower().map({
    'poor': 1, 'fair': 2, 'good': 3, 'excellent': 4
})
df['AI_Tool_Usage'] = df['AI_Tool_Usage'].str.strip().str.lower().map({
    'never': 0, 'rarely': 1, 'sometimes': 2, 'often': 3, 'always': 4
})
df['Year'] = df['Year'].map({
    'Year 1': 1, 'Year 2': 2, 'Year 3': 3, 'Year 4': 4
})
# Save the mapped columns back into df
df['Study_Habit']      = study_habit_num
df['Study_Group_Freq'] = study_group_num
df['Commute_Time']     = commute_hrs
df['Extracurricular']  = extracurricular_num


print(df.dtypes)
print(df.head())

Gender                       int64
Year                       float64
STEM_Major                   int64
Diet_Quality                 int64
Internet_Quality             int64
Employment                   int64
Study_Habit                  int64
Stress_Level               float64
Self_Study_Hrs             float64
Tutoring_Hrs_Wk            float64
AI_Tool_Usage                int64
Social_Media_Hrs           float64
Gaming_Hrs                 float64
Exercise_Days_Wk           float64
Sleep_Hrs                  float64
Attendance_Rate            float64
Commute_Time               float64
Study_Group_Freq             int64
Extracurricular              int64
GPA                        float64
Performance_Tier            object
Total_Productive_Hrs       float64
Distraction_Hrs            float64
Study_Distraction_Ratio    float64
Wellbeing_Score            float64
Available_Study_Time       float64
Active_Engagement_Score    float64
Study_Quality              float64
AI_Enhanced_Study          float64
dtype: object
   Gender  Year  STEM_Major  Diet_Quality  Internet_Quality  Employment  \
0       1   2.0           1             3                 3           0
1       0   1.0           1             4                 3           0
2       1   1.0           1             2                 3           0
3       1   2.0           1             3                 3           0
4       1   2.0           1             2                 2           0

   Study_Habit  Stress_Level  Self_Study_Hrs  Tutoring_Hrs_Wk  ...   GPA  \
0            1           5.5             4.0              0.0  ...  3.39
1            3           5.5             2.0              0.0  ...  3.69
2            2           7.5             3.0              2.0  ...  3.48
3            3           5.5             2.0              0.0  ...  3.50
4            3           7.5             4.0              0.0  ...  3.70

   Performance_Tier  Total_Productive_Hrs  Distraction_Hrs  \
0  Very Good / Good                   4.0              2.0
1  Very Good / Good                   2.0              1.5
2  Very Good / Good                   5.0              5.0
3  Very Good / Good                   2.0              4.0
4  Very Good / Good                   4.0              5.0

   Study_Distraction_Ratio  Wellbeing_Score  Available_Study_Time  \
0                 1.904762              5.0                14.625
1                 1.250000              6.0                14.125
2                 0.588235              1.0                11.875
3                 0.487805             -0.5                14.625
4                 0.784314              0.0                11.750

   Active_Engagement_Score  Study_Quality  AI_Enhanced_Study
0                     11.5            4.0               12.0
1                     10.5            6.0                8.0
2                     12.5            6.0                9.0
3                     11.2            6.0                8.0
4                     11.2           12.0               16.0

[5 rows x 29 columns]

In [46]:
# ============================================================
# ADDITIONAL ENGINEERED FEATURES (No GPA — no leakage)
# ============================================================
# Correlation with Performance_Tier (no GPA):
#   Resource_Quality     +0.603  ★ strongest new feature
#   Lifestyle_Index      +0.587
#   AI_Engagement        +0.533
#   Time_Efficiency      +0.407
#   Digital_Balance      +0.384
#   Academic_Momentum    +0.354
#   Stress_Load          -0.314
#   Study_Consistency    +0.270
#   Stress_Wellbeing     -0.202
# ============================================================

diet_num = df['Diet_Quality']      # already encoded 1-4 from Cell 10
inet_num = df['Internet_Quality']  # already encoded 1-4 from Cell 10

# --- Feature 9: Resource Quality ---
# Diet x Internet synergy — both must be good for effective study
# Strongest new feature: corr +0.603 with Performance_Tier
df['Resource_Quality'] = diet_num * inet_num

# --- Feature 10: Focus Ratio ---
# Total productive hours vs total distraction — measures time discipline
df['Focus_Ratio'] = df['Total_Productive_Hrs'] / (df['Distraction_Hrs'] + 0.1)

# --- Feature 11: Stress-Wellbeing Pressure ---
# High stress on low wellbeing baseline = high academic risk
df['Stress_Wellbeing'] = df['Stress_Level'] / (df['Wellbeing_Score'] + 6)

# --- Feature 12: AI-Powered Engagement ---
# AI tool use x active engagement — tech-enabled learners compound benefits
df['AI_Engagement'] = ai_tool_usage_num * df['Active_Engagement_Score']

# --- Feature 13: Lifestyle Index ---
# Composite of diet, internet, wellbeing — normalized overall life quality
wellbeing_max = df['Wellbeing_Score'].clip(lower=0).max()
df['Lifestyle_Index'] = (
    diet_num / 4 +
    inet_num / 4 +
    df['Wellbeing_Score'].clip(lower=0) / (wellbeing_max + 1e-9)
) / 3

# --- Feature 14: Study Consistency ---
# Study habit strength x group study frequency
# Regular studier who also studies in groups = strongest academic signal
df['Study_Consistency'] = study_habit_num * study_group_num

# --- Feature 15: Time Efficiency ---
# Quality study output relative to stress — high quality under pressure = strong performer
df['Time_Efficiency'] = df['Study_Quality'] / (df['Stress_Level'] + 1)

# --- Feature 16: Digital Balance ---
# AI tool use vs distraction hours — productive vs wasteful screen time ratio
df['Digital_Balance'] = ai_tool_usage_num / (df['Distraction_Hrs'] + 0.1)

# --- Feature 17: Academic Momentum ---
# Active engagement amplified by study habit — showing up + studying consistently
df['Academic_Momentum'] = df['Active_Engagement_Score'] * study_habit_num

# --- Feature 18: Stress Load ---
# Stress x total time burden (distraction + commute) — compound at-risk signal
df['Stress_Load'] = df['Stress_Level'] * (df['Distraction_Hrs'] + commute_hrs)

# ── Verify ───────────────────────────────────────────────────────
new_features = [
    'Resource_Quality', 'Focus_Ratio', 'Stress_Wellbeing',
    'AI_Engagement', 'Lifestyle_Index', 'Study_Consistency',
    'Time_Efficiency', 'Digital_Balance', 'Academic_Momentum', 'Stress_Load'
]
print(f'Added {len(new_features)} new features — no GPA used, no leakage')
print(df[new_features].describe().round(2))

Added 10 new features — no GPA used, no leakage
       Resource_Quality  Focus_Ratio  Stress_Wellbeing  AI_Engagement  \
count            598.00       598.00            598.00         598.00
mean               6.10         1.50              1.04          31.76
std                3.29         2.02              1.47          12.62
min                1.00         0.00              0.09           0.00
25%                4.00         0.39              0.48          23.00
50%                6.00         0.95              0.73          34.25
75%                9.00         1.88              1.25          42.00
max               16.00        20.00             19.00          54.00

       Lifestyle_Index  Study_Consistency  Time_Efficiency  Digital_Balance  \
count           598.00             598.00           598.00           598.00
mean              0.49               3.31             0.93             1.00
std               0.15               2.50             0.88             0.92
min               0.17               0.00             0.00             0.00
25%               0.37               1.00             0.31             0.45
50%               0.50               3.00             0.71             0.78
75%               0.60               6.00             1.37             1.22
max               0.97               9.00             7.20             6.67

       Academic_Momentum  Stress_Load
count             598.00       598.00
mean               23.00        29.04
std                10.79        18.03
min                 5.50         2.44
25%                11.50        14.88
50%                23.00        25.31
75%                34.50        40.31
max                40.50        96.19

In [47]:
df['Performance_Tier'].unique()

array(['Very Good / Good', 'Fair / Average', 'Outstanding / Excellent',
       'At-Risk'], dtype=object)

In [48]:
performance_tier_map = {
    'At-Risk': 0,
    'Fair / Average': 1,
    'Very Good / Good' : 2, 
    'Outstanding / Excellent': 2
}
df['Performance_Tier'] = df['Performance_Tier'].map(performance_tier_map)

In [49]:
df

,Gender,Year,STEM_Major,Diet_Quality,Internet_Quality,Employment,Study_Habit,Stress_Level,Self_Study_Hrs,Tutoring_Hrs_Wk,...,Resource_Quality,Focus_Ratio,Stress_Wellbeing,AI_Engagement,Lifestyle_Index,Study_Consistency,Time_Efficiency,Digital_Balance,Academic_Momentum,Stress_Load
0,1,2.0,1,3,3,0,1,5.5,4.0,0.0,...,9,1.904762,0.500000,34.5,0.658730,1,0.615385,1.428571,11.5,13.0625
1,0,1.0,1,4,3,0,3,5.5,2.0,0.0,...,12,1.250000,0.458333,42.0,0.773810,3,0.923077,2.500000,31.5,10.3125
2,1,1.0,1,2,3,0,2,7.5,3.0,2.0,...,6,0.980392,1.071429,37.5,0.448413,4,0.705882,0.588235,25.0,38.4375
3,1,2.0,1,3,3,0,3,5.5,2.0,0.0,...,9,0.487805,1.000000,44.8,0.500000,6,0.923077,0.975610,33.6,24.0625
4,1,2.0,1,2,2,0,3,7.5,4.0,0.0,...,4,0.784314,1.250000,44.8,0.333333,6,1.411765,0.784314,33.6,46.8750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,0,3.0,1,2,2,0,3,5.5,4.0,5.0,...,4,2.500000,0.500000,38.0,0.492063,0,1.846154,1.111111,28.5,19.9375
594,1,1.0,1,3,2,0,3,5.5,1.0,2.0,...,6,0.833333,0.458333,31.5,0.607143,3,0.461538,0.833333,31.5,21.3125
595,1,1.0,1,3,3,0,3,5.5,4.0,0.0,...,9,0.606061,0.550000,50.0,0.626984,9,1.846154,0.606061,37.5,36.4375
596,1,2.0,1,3,3,1,3,3.5,4.0,2.0,...,9,1.176471,0.318182,25.0,0.658730,9,2.666667,0.392157,37.5,18.8125
597,1,3.0,1,3,2,0,3,7.5,4.0,2.0,...,6,1.463415,0.714286,46.0,0.559524,3,1.411765,0.975610,34.5,35.6250

In [50]:
df.drop(columns=[
    'Self_Study_Hrs',    # → Total_Productive_Hrs, Study_Quality, Study_Distraction_Ratio
    'Tutoring_Hrs_Wk',  # → Total_Productive_Hrs
    'Social_Media_Hrs', # → Distraction_Hrs, Available_Study_Time
    'Gaming_Hrs',       # → Distraction_Hrs, Available_Study_Time
    'Sleep_Hrs',        # → Wellbeing_Score, Available_Study_Time
    'Exercise_Days_Wk', # → Wellbeing_Score
    'Attendance_Rate',  # → Active_Engagement_Score
    'Study_Habit',      # → Study_Quality
    'Study_Group_Freq', # → Active_Engagement_Score
    'Commute_Time',     # → Available_Study_Time
    'Extracurricular',  # → Active_Engagement_Score
], inplace=True)
df

,Gender,Year,STEM_Major,Diet_Quality,Internet_Quality,Employment,Stress_Level,AI_Tool_Usage,GPA,Performance_Tier,...,Resource_Quality,Focus_Ratio,Stress_Wellbeing,AI_Engagement,Lifestyle_Index,Study_Consistency,Time_Efficiency,Digital_Balance,Academic_Momentum,Stress_Load
0,1,2.0,1,3,3,0,5.5,3,3.39,2,...,9,1.904762,0.500000,34.5,0.658730,1,0.615385,1.428571,11.5,13.0625
1,0,1.0,1,4,3,0,5.5,4,3.69,2,...,12,1.250000,0.458333,42.0,0.773810,3,0.923077,2.500000,31.5,10.3125
2,1,1.0,1,2,3,0,7.5,3,3.48,2,...,6,0.980392,1.071429,37.5,0.448413,4,0.705882,0.588235,25.0,38.4375
3,1,2.0,1,3,3,0,5.5,4,3.50,2,...,9,0.487805,1.000000,44.8,0.500000,6,0.923077,0.975610,33.6,24.0625
4,1,2.0,1,2,2,0,7.5,4,3.70,2,...,4,0.784314,1.250000,44.8,0.333333,6,1.411765,0.784314,33.6,46.8750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,0,3.0,1,2,2,0,5.5,4,3.96,2,...,4,2.500000,0.500000,38.0,0.492063,0,1.846154,1.111111,28.5,19.9375
594,1,1.0,1,3,2,0,5.5,3,3.93,2,...,6,0.833333,0.458333,31.5,0.607143,3,0.461538,0.833333,31.5,21.3125
595,1,1.0,1,3,3,0,5.5,4,3.98,2,...,9,0.606061,0.550000,50.0,0.626984,9,1.846154,0.606061,37.5,36.4375
596,1,2.0,1,3,3,1,3.5,2,3.63,2,...,9,1.176471,0.318182,25.0,0.658730,9,2.666667,0.392157,37.5,18.8125
597,1,3.0,1,3,2,0,7.5,4,3.50,2,...,6,1.463415,0.714286,46.0,0.559524,3,1.411765,0.975610,34.5,35.6250

In [51]:
df['Performance_Tier'].unique()

array([2, 1, 0])

In [52]:
df['GPA'].fillna(df['GPA'].median(), inplace=True)
df['Year'].fillna(df['Year'].mode()[0], inplace=True)

C:\Users\MSI\AppData\Local\Temp\ipykernel_20016\633630916.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['GPA'].fillna(df['GPA'].median(), inplace=True)
C:\Users\MSI\AppData\Local\Temp\ipykernel_20016\633630916.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Year'].fillna(df['Year'].mode()[0], inplace=True)

In [53]:
df.isnull().sum()

Gender                     0
Year                       0
STEM_Major                 0
Diet_Quality               0
Internet_Quality           0
Employment                 0
Stress_Level               0
AI_Tool_Usage              0
GPA                        0
Performance_Tier           0
Total_Productive_Hrs       0
Distraction_Hrs            0
Study_Distraction_Ratio    0
Wellbeing_Score            0
Available_Study_Time       0
Active_Engagement_Score    0
Study_Quality              0
AI_Enhanced_Study          0
Resource_Quality           0
Focus_Ratio                0
Stress_Wellbeing           0
AI_Engagement              0
Lifestyle_Index            0
Study_Consistency          0
Time_Efficiency            0
Digital_Balance            0
Academic_Momentum          0
Stress_Load                0
dtype: int64

In [54]:
df.to_csv('preprocessed_data(1).csv', index=False)